### ISSUE TITLE
鸿蒙系统无法使用

### ISSUE THREAD

**Issue by ChengYang1998** [tagbug/ujs.AutoClock.apk#2]
您好鸿蒙系统无法使用，错误：OCR服务异常

**Comment by tagbug** [comment]
> 您好鸿蒙系统无法使用，错误：OCR服务异常

OCR服务异常是因为原来扒的接口失效了，您可以先使用别的自动打卡脚本，最近忙着刷算法，可能修复会晚一些，等修复完成并且测试通过后我会第一时间发布新版本，感谢理解与支持

**Comment by tagbug** [comment]
> 您好鸿蒙系统无法使用，错误：OCR服务异常

已修复
